### ISSUE TITLE
Source code needed, cannot replicate the results regarding consistency under shift on CIFAR-10 as presented in Table 9

### ISSUE THREAD

**Issue by Linwei-Chen** [GeJulia/flc_pooling#2]
I cannot replicate the results regarding consistency under shift on CIFAR-10 as presented in Table 9 of your paper. Could you please provide the source code or more details on the methodology? The paper lacks information such as the specific shift, (padding from 32 to 40, and the subsequent crop to 32?). We intend to cite your paper in our recent research, and having these additional details would be greatly appreciated.

**Comment by GeJulia** [comment]
For evaluating the shift-invariance of our FLC Pooling we used the code provided by [Zhang](https://github.com/adobe/antialiased-cnns/blob/b27a34a26f3ab039113d44d83c54d0428598ac9c/main.py#L549). For the evaluation of lower resolutions (like CIFAR), we used an offset of 4. So you would need to replace the 564 to 568 with the following code snippet: 

```
off0 = np.random.randint(4,size=2)
off1 = np.random.randint(4,size=2)

output0 = model(input[:,:,off0[0]:off0[0]+32,off0[1]:off0[1]+32])
output1 = model(input[:,:,off1[0]:off1[0]+32,off1[1]:off1[1]+32])
```
