### ISSUE TITLE
Unable to replicate the results regarding consistency under shift on CIFAR-10 as presented in Table 9.

### ISSUE THREAD

**Issue by Linwei-Chen** [GeJulia/flc_pooling#3]
Thanks for your reply! I have repeated the experiments and found that the baseline PRN-18 can achieve a consistency of 95.6 under shift. Meanwhile, your FLC also achieves similar results of 95.5.

Experiment details:
I used the code from https://github.com/locuslab/fast_adversarial and made modifications to use clean CIFAR-10 training without AT. All parameters were set following the same settings as described in the paper.

To test the consistency under shift, I bilinearly resized the 32x32 CIFAR images to 36, and the shift was set to 4, following the guidance provided in https://github.com/GeJulia/flc_pooling/issues/2.

**Comment by GeJulia** [comment]
Thanks for letting me know!
