### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by harsmac** [GeJulia/flc_pooling#4]
Hi,
Thanks for releasing the code. Any chance the pretrained models on resnet can be made available?

**Comment by GeJulia** [comment]
Hi @code-Assasin, 
you can find the pretrained weights for ResNet-18, 50, 101 and WideResNet-50-2 via the following link:
https://drive.google.com/drive/folders/1rd3LQ2PXvUmcgrURbpWY1eDC61eyBzMq?usp=sharing

**Comment by harsmac** [comment]
Hi, 
All the architectures in this repository are for cifar10. However, the models in google drive are for imagenet ? Could you include the architectures for the imagenet models?

**Comment by GeJulia** [comment]
Hi,
we released the code for the ResNet on ImageNet now.
If you need further weights on CIFAR10, please let me know!

**Comment by harsmac** [comment]
Thank you for the quick replies. And yes, if you could provide the weights for Cifar would be great !

**Comment by GeJulia** [comment]
Hi, 
sorry for the delay.
Unfortunately, we needed to retrain the CIFAR10 network and added the weights for PreActResNet18 in the folder mentioned above.

**Comment by harsmac** [comment]
Thanks a lot !
