### ISSUE TITLE
Unable to replicate the result in table2

### ISSUE THREAD

**Issue by MingZeGao111** [GeJulia/flc_pooling#5]
I use Preact-ResNet-18 as backbone to replicate the FLC Pooling, using clean and PGD as test metrics and the full dataset of CIFAR-10. 
My experiments parameter is shown in the image. 
![c5e1ef2e8cdeb7266bba8dc9a6838f2](https://github.com/GeJulia/flc_pooling/assets/163491915/20d9a794-3d07-43f7-a0e8-cc56bdcfcc94)
With these parameter, i got 97.14% clean accuracy and 77.10% PGD accuracy, but the result in paper is 84.81% clean accuracy and 38.41 PGD accuracy.

**Comment by GeJulia** [comment]
When you say "full dataset of CIFAR-10" do you evaluate the full data of CIFAR-10 (including training and test data) or do you only evaluate the test data of CIFAR-10?

**Comment by MingZeGao111** [comment]
I evaluate the full data of CIFAR-10 (including training and test data)， is it right？

**Comment by GeJulia** [comment]
No, the training data is supposed to be used only for training and not for testing while the testing data is supposed to be used only for testing and should not be included during training.

**Comment by MingZeGao111** [comment]
ok，thanks very much

**Comment by MingZeGao111** [comment]
![B} 4{_8{4F(GMF7C@QUF_GX](https://github.com/GeJulia/flc_pooling/assets/163491915/e5c4ae99-501c-48f9-adf9-44db50e81553)
Sorry to bother yor again. Now I only use test dataset to test the accuracy of Preact-resnet-18 with FLC pooling on CIFAR-10, I got 83.9% clean accuracy(similar to that in your paper), but I got 1.88%PGD accuracy which is different from the result in your paper. The parameter is mentioned before, what's the problem?
